import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { faker } from '@faker-js/faker';

process.env.FUNCTIONS_EMULATOR = true;
process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8080';

const projectId = 'employee-qualification';
const app = initializeApp({ projectId });
const db = getFirestore(app);

async function getSeedData() {
	try {
		console.log('start adding users');
		const usersPromises = [...Array(500).keys()].map(async () => {
			const user = await db.collection('users').add({
				name: {
					first: faker.person.firstName(),
					last: faker.person.lastName()
				},
				isActive: faker.datatype.boolean(),
				email: faker.internet.email(),
			});
			console.log(`adding ${user.id}`);
			return user.id;
		});
		const proficiencyLevels = ['Basic', 'Intermediate', 'Advanced', 'Expert'];
		const proficencyPromiises = proficiencyLevels.map(async (level) => {
			const prof = await db.collection('proficiencyLevels').add({
				level: level
			});
			return prof.id;
		});
		const degreeLevels = ['Post-Graduate Certificate', 'Associates Degree', 'Bachelor\'s of Art', 'Bachelor\'s of Science', 'Master\'s Degree', 'Doctorate'];
		const educationLevelsPromises = degreeLevels.map(async (level) => {
			const edu = await db.collection('educationLevels').add({
				level: level
			});
			return edu.id;
		});
		const fieldOfStudies = ['Computer Science', 'Engineering', 'Mathematics', 'English', 'History', 'Computer Engineering', 'Computer and Information Technology', 'Information Systems', 'Applied Science', 'CyberSecurity', 'Information Security', 'Accounting', 'General Studies', 'Criminal Justice', 'Public Administration', 'Technology Management', 'Health Information Management', 'Software Engineering', 'Criminology', 'Business Administration', 'Cybersecurity Technology', 'Psychology', 'Sociology', 'National Security ', 'Intelligence and Political Science ', 'Environmental and Natural Resource Economics', 'Computer Science and Engineering'];
		const fieldOfStudyPromises = fieldOfStudies.map(async (field) => {
			const fos = await db.collection('fieldsOfStudy').add({
				field: field
			});
			return fos.id;
		});
		const skills = ['C#',
			'Django',
			'HTML/CSS',
			'Java',
			'JavaScript',
			'Linux Command Line',
			'Oracle SQL',
			'PostgreSQL',
			'Python',
			'.NET',
			'.net compact framework',
			'A/V',
			'ABIS Multi-Modal Biometric Platform',
			'Access',
			'Access Management',
			'Accumulo',
			'Actionscript 2.0 & 3.0',
			'Active Directory',
			'ActiveMQ',
			'Ada',
			'ADF ',
			'ADO',
			'Adobe Flash',
			'Adobe Captivate',
			'Adobe Creative Suite',
			'Adobe DC',
			'Adobe Photoshop ',
			'AIMS',
			'AJAX',
			'Amazon Web Services (AWS) S3 Cloud Storage',
			'AMT',
			'AMX Interface Unit',
			'Android',
			'AngularJS',
			'Ansible',
			'ANT',
			'ANT ',
			'AOL Server',
			'Apache',
			'Apache (Ivy)',
			'Apache NiFi',
			'Apache POI',
			'Apache/Tomcat/MySQL',
			'APEX ',
			'ASP',
			'Assembly',
			'Auth0',
			'Automation',
			'Autoscaling',
			'AVTC',
			'Aware NISTPACK',
			'AWS',
			'AWS (CloudFront)',
			'Azure',
			'Bash Shell',
			'Bootstrap',
			'Boss',
			'BPEL ',
			'BRG Clocks',
			'Business Digital Voice',
			'Business Intelligence - Business Objects Infoview',
			'C',
			'C++ ',
			'Call Manager',
			'CBS Web Portal',
			'Centrex',
			'Cisco Call Management Suite',
			'Cisco Instant Messaging and Presence',
			'Cisco Telepresence Management Suite (TMS)',
			'Cisco Unity',
			'CITRIX',
			'ClearCase',
			'ClearQuest ',
			'CLEC',
			'Cloud',
			'Cloudbase',
			'CloudFormation',
			'CloudTrail',
			'CloudWatch',
			'CMIS',
			'CMS Network',
			'CODEC',
			'CODIAN MCUs',
			'Cofee',
			'CoFEE Dispatch',
			'CoFEE to Go',
			'Cognito',
			'Commerce Business Systems Web Portal and Functional Modules',
			'COMSEC/EKMS',
			'Confluence',
			'Contesa. SQLServer',
			'Continuous Integration',
			'Contribute',
			'CRM systems',
			'Crystal Reports',
			'CSS',
			'CVS',
			'CXF',
			'Data Management',
			'Data Mappings',
			'Data Transformation & Visualization',
			'Database Management',
			'DB2',
			'DHTML',
			'Discoverer',
			'Discoverer Administrator',
			'DocumentDB',
			'DOS Batch',
			'Dreamweaver',
			'DSL',
			'EAI Integration Solutions',
			'EBS',
			'e-Business suite',
			'EC2',
			'Eclipse ',
			'e-Financials',
			'EJB ',
			'ElasticSearch',
			'Enterprise Service Bus (ESB)',
			'ERP',
			'ETL',
			'Excel',
			'Exchange Server',
			'Express',
			'ExpressTRAK',
			'FAX',
			'FDF',
			'fiber optics',
			'FIOS',
			'Firebird',
			'Firewalls',
			'Fortify',
			'FortifySCA',
			'Frame Relay',
			'FTP',
			'GIT',
			'GitHub',
			'GitLab',
			'Glacier',
			'Google BigTable',
			'GWT (Google Web Toolkit)',
			'Hadoop',
			'Heroku',
			'Hibernate ',
			'HP-UX',
			'HSQL',
			'HTML',
			'HTML5 ',
			'IBM iSeries (AS/400)',
			'IBM MQ Series',
			'IBM WebSphere',
			'IGO',
			'IIS',
			'Illustrator',
			'Indexing',
			'Informatica',
			'IntelliJ',
			'iOS',
			'IPM',
			'ISAM',
			'ISDN BRI/PRI',
			'ISIM',
			'iText',
			'ITK',
			'IVAPP',
			'J2EE ',
			'Jasper Soft',
			'Java',
			'Java Script ',
			'Java/eclipse development environment',
			'JAXB ',
			'JAZZ',
			'JBOSS ',
			'JDBC',
			'Jdeveloper ',
			'JEE',
			'Jetty',
			'Jira',
			'JPA',
			'Jquery ',
			'JSF ',
			'JSON',
			'JSP ',
			'JSP/JSTL',
			'JUNG',
			'JUnit',
			'JWICS Scheduling',
			'Kafka',
			'Kerberos',
			'Kibana',
			'Lambda',
			'LAN/ WAN',
			'LeadIQ',
			'LEC',
			'LEC Retain',
			'LEX',
			'Liferay',
			'Linux ',
			'Linux Bash',
			'Linux Shell Scripting',
			'Logstash',
			'MapReduce',
			'Maven',
			'MDU',
			'Meeting Place',
			'Mercurial TortoiseHg',
			'Microsoft .NET',
			'Microsoft Office Suite',
			'Microsoft SharePoint',
			'Microsoft SQL Server',
			'Microsoft Team Foundation Server',
			'Microsoft Visual Studio',
			'Microsoft Windows',
			'MongoDB',
			'MorphoTrust (L-1)',
			'MS Access',
			'MS Office Suite',
			'MS Project',
			'MS Publisher',
			'MS SharePoint',
			'MS SQL',
			'MS SQL Server',
			'MS Team',
			'MS.NET Visual Studio 2005 ',
			'MS-Excel',
			'MS-Office (Word)',
			'MVC',
			'MYSQL ',
			'Network Architecture',
			'Network Security',
			'Networking',
			'Nginx',
			'NHibernate',
			'NiagaraFiles (NiFi)',
			'NIEM',
			'NodeJS',
			'Nokia Newelo software',
			'NoSQL',
			'NRI Console',
			'NSOP',
			'Ntag',
			'NTARS',
			'NTAS/NTAG',
			'Oracle',
			'Oracle 10g',
			'Oracle 12C',
			'Oracle Apex',
			'Oracle Application Server',
			'Oracle Designer',
			'Oracle Discoverer',
			'Oracle ERP',
			'Oracle Forms',
			'Oracle JDeveloper 10',
			'Oracle Packages',
			'Oracle SQL Data Modeler 3.0',
			'Oracle SQL Developer',
			'OWF (Ozone Wedget Framework)',
			'PBX',
			'Pega ',
			'Perl',
			'Perl/TK',
			'Pervasive',
			'PGP Encryption',
			'Photoshop',
			'PHP',
			'PHP ',
			'PHP 4+',
			'PITK',
			'PKI',
			'PL SQL',
			'PL/SQL',
			'PL/SQL ',
			'Polycom',
			'Postgres',
			'PostgreSQL',
			'POTS',
			'Power Automate',
			'Power Bi',
			'Power Point',
			'PowerApps',
			'Progress',
			'Project',
			'Prototype',
			'PyQT',
			'Python',
			'Python',
			'QT Creator',
			'QT Designer',
			'Quest TOAD',
			'Rational ClearCase',
			'Rational ClearCase 7.1',
			'Rational ClearQuest',
			'Rationale Suite',
			'RDS',
			'React Native',
			'Red Hat',
			'Reports',
			'REST',
			'rest services',
			'Restful API',
			'RHEL',
			'Routers',
			'Ruby',
			'S3',
			'SalesLoft',
			'SAML',
			'SCORM',
			'Scriptaculous',
			'Scripting',
			'Security',
			'Service Oriented Architecture (SOA)',
			'SFTP',
			'SharePoint',
			'SharePoint Administration',
			'Shell',
			'Shell Scripts',
			'Siebel',
			'SMS',
			'SMTP',
			'SNS',
			'SOAP',
			'socket.io',
			'Software Installation',
			'Solaris',
			'Sparx Enterprise Architect',
			'Spring Framework',
			'Sprint MVC ',
			'SQL',
			'SQL Assistant',
			'SQL Developer',
			'SQL Script SQL Loader',
			'SQL Server',
			'SQL*Loader',
			'SQL*Plus',
			'SQS',
			'SSO (Keycloak)',
			'SSP Order & Workflow',
			'STE',
			'Storage Arrays',
			'Storm/Spout/Bolt Topologies',
			'Struts',
			'Sun Application',
			'SVN',
			'SVTC',
			'Switches',
			'Switches Level 2 & 3',
			'System Administration',
			'T1',
			'TACLANE',
			'TCP/IP',
			'Telecommunication',
			'TEM(Telecom Expense Management) Ordering and Billing',
			'TEM(Telecom Expense Management)TSS',
			'Teradata',
			'Terraform',
			'TestNG',
			'TIBCO',
			'TOAD',
			'Tomcat',
			'Trac',
			'TrackIT',
			'Troubleshooting',
			'Twilio',
			'TypeScript',
			'Ubuntu',
			'UCM',
			'Unix',
			'Unix Shell Script',
			'Unix Shell Scriptings',
			'UNIX/Solaris',
			'VBA for Office',
			'VBScript',
			'VC++',
			'VDI',
			'vIPer',
			'Visio',
			'Visio',
			'Visual Basic',
			'Visual Basic ',
			'Visual Studio ',
			'Visual Studio 2016',
			'VM',
			'VMWare',
			'VOIP',
			'VoSIP',
			'VPC',
			'VPN Tunneling',
			'VSS',
			'WAFA',
			'web design',
			'Web Services',
			'WebLogic',
			'WebSphere',
			'Wikis',
			'Windows (all versions)',
			'Windows Server',
			'Wireless',
			'XCOTA',
			'XHTML',
			'XML',
			'XML ',
			'XML Parsing',
			'XPATH',
			'XPATH ',
			'XSD ',
			'XSLT',
			'XSLT ',
			'YUI',
			'ZooKeeper',
			'Ansible',
			'Powershell']
		const skillsPromises = skills.map(async (skill) => {
			const sk = await db.collection('skills').add({
				skill: skill
			});
			return sk.id;
		});
		const certs = ['Software Programming', 'Pega Certified System Architect', 'Security+', 'CompTIA Project+ ', 'CompTIA Security+ ', 'CompTIA Network+ ', 'CompTIA A+ Practical Application ', 'Java SE 7 Programmer ', 'Web Development Technical Certificate ', 'Lean Six Sigma', 'Certified Scrum Master (CSM)', 'Projec5t Management Professional (PMP)', 'Program Management Professional (PgMP)', 'SAFe SM', 'SAFe Agilist', 'SAFe RTE', 'Microsoft: 70-778: Analyzing and Visualizing Data with Microsoft Power BI', 'DM Certified Designer– 4K (DMC-D-4K)', 'DM Certified Technician– 4K (DMC-T-4K)', 'Crestron Certified Audio Technician', 'DM Certified Engineer – 4K (DMC-E-4K)', 'DM Certification Streaming (DMC-S)', 'Oracle Database 12c: SQL Fundamentals', 'AWS Certified Developer', 'Microsoft Specialist HTML5 JavaScript', 'AWS Certified Solutions Architect', 'ICAgile Certified Professional (ICP)', 'CMA 4000/5000 Technical Operations', 'InfoComm CTS-D', 'InfoComm CTS-I', 'Extron Control Specialist', 'AMX Digital Signage Expert', 'Biamp Tesira, Audia', 'Java Programming and Software Engineering', 'Python Programming', 'Cisco Certified Technician Telepresence', 'HDBaseT Expert Installer', 'Harman Certified Control Associate: Programming', 'Harman Certified Control Associate: Programming', 'Planar LED/LCD Wall Certification', 'Extron Certified XTP Systems Technician', 'Cisco Certified Specialist-Collaboration Core ', 'VQ Conference Manager Concierge and Call Management ', 'VQ Conference Manager Deployment and System Administration', 'A+', 'Oracle SQL Associate', 'AWS Cloud Practitioner', 'Oracle Fusion Middleware – BPEL', 'Oracle Applications Framework ', 'Oracle Application Development Framework ', 'Oracle Workflow Builder 2.6 ', 'ITIL V3'];
		const certificationPromises = certs.map(async (cert) => {
			const certification = await db.collection('certifications').add({
				name: cert
			});
			return certification.id;
		});
		const otherTrainings = ['NIEM XML Training', 'Building XML Web Services with Java', 'Developing Java Web Applications', 'Azure Fundamentals', 'SAFe Advanced Scrum Master (SASM)', 'Project Management Professional ', 'VBrick Network Certified Engineer', 'AMX Programming', 'Crestron Programming training', 'Oracle Forms and Reports', 'Crystal Reports', 'Oracle Applications 11i Bootcamp', 'Oracle Developer Bootcamp (SQL, PL/SQL, Developer 6i, Java) '];
		const trainingPromises = otherTrainings.map(async (training) => {
			const trn = await db.collection('otherTraining').add({
				topic: training
			});
			return trn.id;
		});
		const clearanceLevels = ['TS/SCI', 'TS/SCI w/ CI Poly)', 'TS/SCI w/ FS Poly', 'TS', 'SECRET', 'CONFIDENTIAL', 'Public Trust', 'DOE-Q', 'DOE-L'];
		const clearenceLevelsPromises = clearanceLevels.map(async (level) => {
			const cl = await db.collection('clearanceLevels').add({
				level: level
			});
			return cl.id;
		});

		await Promise.all([...usersPromises, ...proficencyPromiises, ...educationLevelsPromises, ...fieldOfStudyPromises, ...skillsPromises, ...certificationPromises, ...trainingPromises, ...clearenceLevelsPromises]);
		console.log('finished adding users, proficiency levels, education levels, fields of study, skills and certifications');
		const empPromises = [...Array(200).keys()].map(async (key, idx) => {
			const emp = await db.collection('employees').add({
				name: {
					first: faker.person.firstName(),
					last: faker.person.lastName()
				},
				skills: [
					{ skill: faker.person.jobDescriptor(), yearsExperience: faker.number.int({ min: 0, max: 20 }), proficiency: faker.helpers.arrayElement(proficiencyLevels) },
					idx % 2 === 0 ? { skill: faker.person.jobType(), yearsExperience: faker.number.int({ min: 0, max: 20 }), proficiency: faker.helpers.arrayElement(proficiencyLevels) } : null
				],
				education: [
					{
						degree: faker.helpers.arrayElement(degreeLevels),
						institution: faker.company.name(),
						fieldOfStudy: faker.helpers.arrayElement(fieldOfStudies)
					},
					idx % 2 === 0 ? {
						degree: faker.helpers.arrayElement(degreeLevels),
						institution: faker.company.name(),
						fieldOfStudy: faker.helpers.arrayElement(fieldOfStudies)
					} : null
				],
				otherTrainings: [
					faker.helpers.arrayElement(otherTrainings),
					idx % 2 === 0 ? faker.helpers.arrayElement(otherTrainings) : null
				],
				clearanceLevel: faker.helpers.arrayElement(clearanceLevels),
				certifications: [{
					name:faker.helpers.arrayElement(certs),
					issuedBy: faker.company.name(),
					yearIssued: faker.date.past({
						years: 3,
						refDate: new Date()
					}),
					expirerationYear: faker.date.future({
						years: 3,
						refDate: new Date()
					})
				}]
			});
			return emp.id;
		});
	} catch (e) {
		console.log(e);
	}
}

getSeedData();
